version: "3"

services:
  svc-api:
    build: .
    restart: always
    image: svc-api:test
    container_name: svc-api
    ports:
      - 7960:7960
    volumes:
      - ./conf:/opt/config
      - ./parameter:/opt/parameter
      - ./logs:/data/logs/apiw4
    environment:
      - JAVA_OPTS=-Xmx256M -Dspring.config.location=config/application.properties -Duser.timezone=GMT+08

  nginx:
    restart: always
    image: nginx:1.18
    container_name: mynginx
    ports:
      - 8087:80
    volumes:
      - ./nconf/nginx.conf:/etc/nginx/nginx.conf
      # - ./conf/conf.d:/etc/nginx/conf.d
      - ./nlogs:/var/log/nginx
      - ./www:/usr/share/nginx/html/
    depends_on:
      - svc-api

networks:
  elk:
    driver: bridge