version: '3'

services:
  nginx:
    restart: always
    image: docker.io/nginx
    container_name: mynginx
    ports:
      - 80:8080
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./conf/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      # - ./www:/var/www
    # command:
    #   - nginx
    #   - --g
    #   - daemon off