version: '3.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    # old version
    # command: server /data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    logging:
      options:
        max-size: "50M"
        max-file: "10"
      driver: json-file
    volumes:
      - /var/dlp/data/minio/data:/data