version: "3"

services:
  influxdb:
    image: influxdb:1.8.3-alpine
    container_name: influxdb
    volumes:
      - ./conf:/etc/influxdb
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    restart: always
