version: "3"

services:
  redis:
    image: redis:5.0.9
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    # network_mode: bridge
    command: redis-server /usr/local/etc/redis/redis.conf
    # command: redis-server --requirepass 123456
